# Pre-commit hooks related config.
[tool.pycln]
all = true

[mypy]
python_version = 3.8
ignore_missing_imports = true

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.black]
line-length = 88
